- hosts: cluster
  sudo: yes
  tasks:
    - name: Install Fortran
      apt: pkg=gfortran update_cache=yes state=installed cache_valid_time=3600

    - name: MKDIR MPICH2
      file: path=/home/pi/mpich2 state=directory

    - name: INSTALL MPICH2
      get_url: url=http://www.mcs.anl.gov/research/projects/mpich2/downloads/tarballs/1.4.1p1/mpich2-1.4.1p1.tar.gz dest=/home/pi/mpich2

    - name: UNARCHIVE MPICH2
      unarchive: src=/home/pi/mpich2/mpich2-1.4.1p1.tar.gz dest=/home/pi/mpich2 copy=no creates=mpich2-1.4.1p1

    - name: MKDIR INSTALL
      file: path=/home/pi/mpich2/install state=directory

    - name: MKDIR BUILD
      file: path=/home/pi/mpich2/build state=directory

    - name: Install make
      apt: name=make update_cache=yes state=installed cache_valid_time=3600

    - name: CONFIGURE MPICH2
      command: /home/pi/mpich2/mpich2-1.4.1p1/configure --prefix=/home/pi/mpich2/install chdir=/home/pi/mpich2/build

    - name: Make
      command: make chdir=/home/pi/mpich2/build

    - name: Make Install
      command: make install chdir=/home/pi/mpich2/build

    - name: SET PATH
      lineinfile: dest=/home/pi/.profile line='PATH=$PATH:/home/pi/mpich2/install/bin' insertafter=EOF
